server:
  port: 30241
  servlet:
    context-path: /api/v1/archive-manager
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESQL_URL}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
management:
  endpoints:
    web:
      exposure:
        include: "health, metrics, prometheus"
  metrics:
    export:
      prometheus:
        enabled: true