server:
  port: 30241
  servlet:
    context-path: /api/v1/archive-manager
spring:
  profiles:
    active: ${PROFILE:}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESQL_URL}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}
    org:
      springframework: ${LOGGING_LEVEL_SPRING:info}
      hibernate: ${LOGGING_LEVEL_HIBERNATE:info}

archivemanager:
  ratelimit: ${ARCHIVEMANAGER_RATELIMIT:10}
