#http://localhost:30241/api/v1/archive-manager/h2-console
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:\\Users\\patsalyuk-as\\Projects\\learning\\ArchiveManager\\src\\main\\resources\\archive-manager
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  level:
    root: info
    org:
      springframework: info
      hibernate: info
