server:
  port: 30241
  servlet:
    context-path: /api/v1/archive-manager
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://db.sbercode-b275cae5-3a4b-41e9-9c0f-d1ae795d5076-work.svc.cluster.local:5432/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
management:
  endpoints:
    web:
      exposure:
        include: "health, metrics, prometheus"
  metrics:
    export:
      prometheus:
        enabled: true