kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.name.cm.dbConfig }}
data:
  POSTGRESQL_URL: "jdbc:postgresql://db-am.{{ .Values.oc.namespace }}.svc.cluster.local:30242"
  POSTGRESQL_USERNAME: archive
  POSTGRESQL_DATABASE: archive_db