kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.name.ingress.app }}
  labels:
    app: {{ .Values.label.ingress.app }}
spec:
  rules:
    - host: "{{ .Values.oc.namespace }}.{{ .Values.app.domain }}"
      http:
        paths:
          - path: /api/v1/archive-manager
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name.service.app }}
                port:
                  name: {{ .Values.name.port.app }}