kind: ConfigMap
apiVersion: v1
metadata:
  name: db-init-config
data:
  init-db.sql: |
    DROP TABLE IF EXISTS Documents;
    DROP TABLE IF EXISTS Boxes;
    CREATE TABLE Boxes 
    (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(20) NOT NULL UNIQUE
    );
    CREATE TABLE Documents (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    BOX INT,
    foreign key (BOX) references Boxes(ID)
    );
    INSERT INTO Boxes (NAME,CODE) VALUES
    ('Box1','b0001'),
    ('Box2','b0002'),
    ('Box3','b0003'),
    ('Box4','b0004');
    INSERT INTO Documents (NAME, CODE, BOX) VALUES
    ('Document1', 'd000001', 1),
    ('Document2', 'd000002', 2),
    ('Document3', 'd000003', 3),
    ('Document4', 'd000004', 4),
    ('Document5', 'd000005', 1),
    ('Document6', 'd000006', 2),
    ('Document7', 'd000007', 1),
    ('Document8', 'd000008', 4);
    INSERT INTO Documents (NAME, CODE) VALUES
    ('Document9', 'EmptyBox1'),
    ('Document10', 'EmptyBox2');