kind: ConfigMap
apiVersion: v1
metadata:
  name: db-config
data:
  POSTGRESQL_URL: jdbc:postgresql://db.sbercode-daa5fdcc-1e12-40ad-9d86-2145267f434c-work.svc.cluster.local:5432
  POSTGRESQL_USERNAME: archive
  POSTGRESQL_DATABASE: archive_db
