kind: Deployment
apiVersion: apps/v1
metadata:
  name: archive-manager
  labels:
    app: archive-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archive-manager
  template:
    metadata:
      labels:
        app: archive-manager
    spec:
      containers:
        - name: archive-manager-cont
          image: pazas/archive-manager:1.0.5
          ports:
            - name: app-am-port
              containerPort: 30241
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/v1/archive-manager/actuator/health
              port: app-am-port
            initialDelaySeconds: 30
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/v1/archive-manager/actuator/health
              port: app-am-port
            initialDelaySeconds: 30
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: archive-manager-config-volume
              mountPath: /app/config/
          envFrom:
            - configMapRef:
                name: db-am-config
            - secretRef:
                name: db-am-secret
      volumes:
        - name: archive-manager-config-volume
          configMap:
            name: archive-manager-config