kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: archive-manager-ingress
  labels:
    app: archive-manager-ingress
spec:
  rules:
    - host: sbercode-b275cae5-3a4b-41e9-9c0f-d1ae795d5076-work.apps.sbc-okd.pcbltools.ru
      http:
        paths:
          - path: /api/v1/archive-manager
            pathType: Prefix
            backend:
              service:
                name: archive-manager-service
                port:
                  name: am-svc-port