kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: db-am
  labels:
    app: am-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-am-selector
  template:
    metadata:
      labels:
        app: db-am-selector
    spec:
      containers:
        - name: postgres-containers
          image: bitnami/postgresql:15
          ports:
            - name: am-postgr-port
              containerPort: 5432
          volumeMounts:
            - name: db-am-init-volume
              mountPath: /docker-entrypoint-initdb.d/
          envFrom:
            - configMapRef:
                name: db-am-config
            - secretRef:
                name: db-am-secret
      volumes:
        - name: db-am-init-volume
          configMap:
            name: db-am-init-config