replicaCount: 1

image:
  db:
    repository: bitnami/postgresql
    pullPolicy: IfNotPresent
    tag: "15"
  app:
    repository: pazas/archive-manager
    pullPolicy: IfNotPresent
    tag: "1.0.6"

selector:
  ss:
    db: db-am-selector
  service:
    db: db-am-selector
  deployment:
    app: archive-manager

label:
  ss:
    db: am-postgres
  ingress:
    app: archive-manager-ingress
  deployment:
    app: archive-manager

name:
  deployment:
    app:  archive-manager
    container: archive-manager-cont
  ss:
    container: db-am-container
    db: db-am
  cm:
    dbConfig: db-am-config
    dbInitConfig: db-am-init-config
    appConfig: archive-manager-config
  secret:
    dbSecret: db-am-secret
  volume:
    dbInitVolume: db-am-init-volume
    appConfig: archive-manager-config-volume
  port:
    postgresqlContainer: am-postgr-port
    postgresql: am-postgres
    appContainer: app-am-port
    app: am-svc-port
  service:
    db: db-am
    app: archive-manager-service
  ingress:
    app: archive-manager-ingress

port:
  postgresqlContainer: 5432
  postgresql: 30242
  appContainer: 30241
  app: 30241

resourcesDB:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

resourcesApp:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

app:
  failureThreshold: 10
  initialDelaySeconds: 30
  host: sbercode-689e7374-cfe7-49ba-9229-d452f66d1284-work.apps.sbc-okd.pcbltools.ru
  domain: apps.sbc-okd.pcbltools.ru

oc:
  namespace: sbercode-689e7374-cfe7-49ba-9229-d452f66d1284-work